# Generated by Django 3.1.5 on 2021-01-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
